### PR TITLE
added navigation component

### PR DESCRIPTION
**Pull request by MonikaJhingan**
Please review.

### CODE REVIEW

**Review by j24m — APPROVED** [review]
Hello, this is again a minor change and can be pushed without raising a PR.

**Review by codewithrishu — APPROVED** [review]
looks good to merge

**Review by Sindhu983 — APPROVED** [review]

**Review by pradipgharge — APPROVED** [review]
Very minor change, looks good to merge

**Comment by MonikaJhingan** [comment]
Thanks all

**Pull request merged**
