### PR TITLE
added text utility component

### PR DESCRIPTION
**Pull request by MonikaJhingan**
Please review it.

### CODE REVIEW

**Review by j24m — APPROVED** [review]
Didn't find anything because the PR is way too small, for changes as minor as this you can directly merge without raising PR.

**Comment by hussiantabha** [comment]
Yes there is nothing to review as this is very small

**Review by saadahmadhere — COMMENTED** [review]
Nothing much to review.

**Review by vanshitalavange — COMMENTED** [review]
not much to review, can be merged

**Pull request merged**
